version: '2'

services:
  bajagym:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bajagym
      - MYSQL_USER=bajagymadmin      
      - MYSQL_PASSWORD=4dm1nch4v3z      
      - MYSQL_ROOT_PASSWORD=4dm1nch4v3z
    ports:
      - 3333:3306
    container_name: bajagym-db


  bajagym-app:
    image: bajagym-image
    build: .
    depends_on:
      - bajagym
    links:
      - bajagym
    ports:
      - 5000:8443
    environment:
        INTERNALSERVICE_BASEURI: http://bajagyminterno-app:8181/internal
        SPRING_DATASOURCE_URL: jdbc:mysql://bajagymdb:3306/bajagyminternal
    restart: on-failure
    container_name:  bajagym-app


  bajagymdb2:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=bajagyminternal      
      - MYSQL_USER=bajagymadmin      
      - MYSQL_PASSWORD=4dm1nch4v3z      
      - MYSQL_ROOT_PASSWORD=4dm1nch4v3z
    ports:
      - 3334:3306
    links:
      - bajagym
    container_name: bajagyminteral-db


  bajagyminterno-app:
    image: bajagyminterno-image
    build: 
        context: .
        dockerfile: Dockerfile-internal
    environment:
       SPRING_DATASOURCE_URL: jdbc:mysql://bajagymdb2:3306/bajagyminternal
    depends_on:
      - bajagymdb2
    links:
      - bajagymdb2
    ports:
      - 5001:8181
    restart: on-failure
    container_name:  bajagyminterno-app
  